M48
; DRILL file {KiCad 6.0.10-86aedd382b~118~ubuntu20.04.1} date So 08 Jän 2023 02:49:32
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-08T02:49:32+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.10-86aedd382b~118~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
%
G90
G05
T1
X111.5Y-128.5
X134.5Y-95.5
T0
M30
